---
apiVersion: v1
kind: ReplicationController
metadata:
  name: kubapp
spec:
  replicas: 3
  selector:
    app: kubapp
  template:
    metadata:
      labels:
        app: kubapp
    spec:
      containers:
      - name: kubapp
        image: evalle/kubapp
...
